### ISSUE TITLE
That is very audacious

### ISSUE THREAD

**Issue by KaitoZerjoYT** [t-starks/MCPEDiscord#2]
It may not concern me directly, but I still find it absolutely cheeky to simply take over a plugin from someone else. Such actions harm the community. Just because GamerMJayy's plugin is reasonably well-known, do you think you can also get a piece of the pie?

GamerMJay is only continuing the plugin because the original developer put it on ice, and unlike you, he gives credit. 
So, take down your version because it's simply a 1-to-1 copy of GamerMJay's, except you've written your name into the plugin, which is beyond audacious.

**Comment by GamerMJay** [comment]
@t-starks

**Comment by t-starks** [comment]
Hello,

I am very sorry for the misunderstanding. My intention was never to take credit for GamerMJayy's work. I'm working on a personal project to learn more about developing plugins for Minecraft and used GamerMJayy's plugin as a reference. I understand the importance of giving credit and will make modifications as necessary to ensure the original work is properly acknowledged.

I appreciate your concern for the community and will ensure I act ethically in the future.

Thanks for pointing this out.

T. Stark
